### ISSUE TITLE
Thoughts?

### ISSUE THREAD

**Issue by RussellHaley** [Tieske/luawinmake#17]
So this little tidbit uses bitsadmin and 7-Zip to get the sources. It would be just as easy to add the gnu tar for windows like Luarocks does. Thoughts?

SET VER=5.3.4
bitsadmin  /transfer download_lua  /download  /priority normal  ^
                  https://www.lua.org/ftp/lua-%VER%.tar.gz  C:\Users\russh\Downloads\lua-%VER%.tar.gz

c:\"program files"\7-Zip\7z.exe x C:\Users\russh\Downloads\lua-%VER%.tar.gz -so | c:\"program files"\7-Zip\7z.exe x -aoa -si -ttar -o"C:\temp"

**Comment by Tieske** [comment]
Not sure what this is? `luawinmake` doesn't download anything? Are you posting this on the right repo?

**Comment by RussellHaley** [comment]
I was considering writing a wrapper script and that was my awkward way of asking if you cared or were interested. :)

**Comment by Tieske** [comment]
similar to what LuaWinMulti does no?

**Comment by RussellHaley** [comment]
Closing due to embarrassment. Looking forward to trying LuaWinMulti. :-)
