### ISSUE TITLE
Allow build without set COMPATFLAG.

### ISSUE THREAD

**Issue by moteus** [Tieske/luawinmake#4]
It very handy use this bat file.
I think it should be command line switch to off all compat flags.
It will be very handy to build Lua on test environment to test modules in strict mode for compatability with specific Lua version.

**Comment by Tieske** [comment]
just pushed an update that adds a `--nocompat` flag

**Comment by ignacio** [comment]
It's only working for MinGW. The codepath for MSVC still builds with /DLUA_COMPAT_ALL

**Comment by Tieske** [comment]
Just pushed a fix. Thx for the report!

**Comment by ignacio** [comment]
Thanks!
