### ISSUE TITLE
Lua installation is failing on AppVeyor

### ISSUE THREAD

**Issue by starius** [Tieske/luawinmake#5]
Hi,

I use [lua-appveyor-example](https://github.com/ignacio/lua-appveyor-example) to run unit tests on Windows (AppVeyor). lua-appveyor-example [uses](https://github.com/ignacio/lua-appveyor-example/blob/master/.appveyor/install.bat#L112) luawinmake. Commit 6823e50d8eecdecaa0 of luawinmake seems to [break my build](https://ci.appveyor.com/project/starius/lua-npge/build/0.0.1.56-test/job/5q1uhoyc371os2cr#L180).

Error message:

```
Checking source code to extract Lua version...
Lua version found: 5.1

Testing for MS...
Microsoft (R) C/C++ Optimizing Compiler Version 18.00.31101 for x86
Copyright (C) Microsoft Corporation. All rights reserved.

usage: cl [ option... ] filename... [ /link linkoption... ]
Using Microsoft toolchain...

( was unexpected at this time.
Command exited with code 255
```

Log of [passing build](https://ci.appveyor.com/project/starius/lua-npge/build/0.0.1.55-test/job/31mhd6r5f81e2iwc) that used previous state of luawinmake:

```
Checking source code to extract Lua version...
Lua version found: 5.1

Testing for MS...
Microsoft (R) C/C++ Optimizing Compiler Version 18.00.31101 for x86
Copyright (C) Microsoft Corporation. All rights reserved.

usage: cl [ option... ] filename... [ /link linkoption... ]
Using Microsoft toolchain...

Now compiling CORE file set...
cl /nologo /MD /O2 /W3 /c /D_CRT_SECURE_NO_DEPRECATE -DLUA_BUILD_AS_DLL lapi.c
lapi.c
cl /nologo /MD /O2 /W3 /c /D_CRT_SECURE_NO_DEPRECATE -DLUA_BUILD_AS_DLL lcode.c
lcode.c
cl /nologo /MD /O2 /W3 /c /D_CRT_SECURE_NO_DEPRECATE -DLUA_BUILD_AS_DLL ldebug.c
ldebug.c
cl /nologo /MD /O2 /W3 /c /D_CRT_SECURE_NO_DEPRECATE -DLUA_BUILD_AS_DLL ldo.c
ldo.c
cl /nologo /MD /O2 /W3 /c /D_CRT_SECURE_NO_DEPRECATE -DLUA_BUILD_AS_DLL ldump.c
ldump.c
...
```

**Comment by ignacio** [comment]
Either VERSIONED needs to have a default value, or tested using quotes, asi in `if "%VERSIONED%"=="TRUE" (`

**Comment by Tieske** [comment]
apologies!!! my bad, should be fixed now.

**Comment by starius** [comment]
Works for me. Thanks!
